### ISSUE TITLE
EMAILADDRESS pattern does not handle multiple edge cases

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/grokky#3]
See https://github.com/crowdsecurity/grokky/blob/master/base.go#L49

**Comment by LaurenceJJones** [comment]
Edge cases:

- Single character emails
- Emails starting with numbers

**Comment by AlpenFlizzer** [comment]
Will there be a fix anywhere soon?

**Comment by LaurenceJJones** [comment]
> Will there be a fix anywhere soon?
> 

There are some issues with issuing a fix, since this is a dependency of CrowdSec the fix will only propogate down when there a new release of CrowdSec. Since this was found late in the cycle we are stuck with a mid August release since there needs to be testing of the new features.

We can issue a fix per parser that uses email address grok pattern as a workaround for now but we need to update this library to not use hardcoded patterns and only get them from the patterns directory.

**Comment by LaurenceJJones** [comment]
Closing issue as merged in lib: another PR will follow to update dependencies to CrowdSec

And will be tracked by [this issue](https://github.com/crowdsecurity/crowdsec/issues/3205)
